### ISSUE TITLE
Cordova Build Android Failing

### ISSUE THREAD

**Issue by foward** [CognitiveBuild/WatsonSpeechPluginSample#1]
Franciscos-MacBook-Pro:WatsonSpeechPluginSample friveros$ cordova build
Android Studio project detected
ANDROID_HOME=/Users/friveros/Library/Android/sdk
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home
studio

BUILD SUCCESSFUL in 1s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
publishNonDefault is deprecated and has no effect anymore. All variants are now published.
Configuration 'debugCompile' in project ':app' is deprecated. Use 'debugImplementation' instead.
Configuration 'releaseCompile' in project ':app' is deprecated. Use 'releaseImplementation' instead.
The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0. Please use Task.doLast(Action) instead.
	at build_25bq2tkohl5ug2gc0tl0f2c60.run(/Users/friveros/Documents/PROJECTS/EXPERT ASSIST/WatsonSpeechPluginSample/platforms/android/app/build.gradle:144)
:CordovaLib:preBuild UP-TO-DATE
:CordovaLib:preDebugBuild UP-TO-DATE
:CordovaLib:compileDebugAidl
:CordovaLib:compileDebugRenderscript
:CordovaLib:checkDebugManifest
:CordovaLib:generateDebugBuildConfig
:CordovaLib:prepareLintJar
:CordovaLib:generateDebugResValues
:CordovaLib:generateDebugResources
:CordovaLib:packageDebugResources
:CordovaLib:platformAttrExtractor
:CordovaLib:processDebugManifest
:CordovaLib:javaPreCompileDebug
:CordovaLib:processDebugJavaRes NO-SOURCE
:app:preBuild UP-TO-DATE
:app:preDebugBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find :speech-android-wrapper-debug:.
  Searched in the following locations:
      file:/Users/friveros/Library/Android/sdk/extras/m2repository//speech-android-wrapper-debug//speech-android-wrapper-debug-.pom
      file:/Users/friveros/Library/Android/sdk/extras/m2repository//speech-android-wrapper-debug//speech-android-wrapper-debug-.aar
      file:/Users/friveros/Library/Android/sdk/extras/google/m2repository//speech-android-wrapper-debug//speech-android-wrapper-debug-.pom
      file:/Users/friveros/Library/Android/sdk/extras/google/m2repository//speech-android-wrapper-debug//speech-android-wrapper-debug-.aar
      file:/Users/friveros/Library/Android/sdk/extras/android/m2repository//speech-android-wrapper-debug//speech-android-wrapper-debug-.pom
      file:/Users/friveros/Library/Android/sdk/extras/android/m2repository//speech-android-wrapper-debug//speech-android-wrapper-debug-.aar
      https://jcenter.bintray.com//speech-android-wrapper-debug//speech-android-wrapper-debug-.pom
      https://jcenter.bintray.com//speech-android-wrapper-debug//speech-android-wrapper-debug-.aar
      https://maven.google.com//speech-android-wrapper-debug//speech-android-wrapper-debug-.pom
      https://maven.google.com//speech-android-wrapper-debug//speech-android-wrapper-debug-.aar
      https://repo1.maven.org/maven2//speech-android-wrapper-debug//speech-android-wrapper-debug-.pom
      https://repo1.maven.org/maven2//speech-android-wrapper-debug//speech-android-wrapper-debug-.aar
      file:/Users/friveros/Documents/PROJECTS/EXPERT ASSIST/WatsonSpeechPluginSample/platforms/android/app/WatsonSpeechPlugin/speech-android-wrapper-debug-.aar
      file:/Users/friveros/Documents/PROJECTS/EXPERT ASSIST/WatsonSpeechPluginSample/platforms/android/app/WatsonSpeechPlugin/speech-android-wrapper-debug.aar
  Required by:
      project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
11 actionable tasks: 11 executed
(node:95852) UnhandledPromiseRejectionWarning: Error: /Users/friveros/Documents/PROJECTS/EXPERT ASSIST/WatsonSpeechPluginSample/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':app:debugCompileClasspath'.
> Could not find :speech-android-wrapper-debug:.
  Searched in the following locations:
      file:/Users/friveros/Library/Android/sdk/extras/m2repository//speech-android-wrapper-debug//speech-android-wrapper-debug-.pom
      file:/Users/friveros/Library/Android/sdk/extras/m2repository//speech-android-wrapper-debug//speech-android-wrapper-debug-.aar
      file:/Users/friveros/Library/Android/sdk/extras/google/m2repository//speech-android-wrapper-debug//speech-android-wrapper-debug-.pom
      file:/Users/friveros/Library/Android/sdk/extras/google/m2repository//speech-android-wrapper-debug//speech-android-wrapper-debug-.aar
      file:/Users/friveros/Library/Android/sdk/extras/android/m2repository//speech-android-wrapper-debug//speech-android-wrapper-debug-.pom
      file:/Users/friveros/Library/Android/sdk/extras/android/m2repository//speech-android-wrapper-debug//speech-android-wrapper-debug-.aar
      https://jcenter.bintray.com//speech-android-wrapper-debug//speech-android-wrapper-debug-.pom
      https://jcenter.bintray.com//speech-android-wrapper-debug//speech-android-wrapper-debug-.aar
      https://maven.google.com//speech-android-wrapper-debug//speech-android-wrapper-debug-.pom
      https://maven.google.com//speech-android-wrapper-debug//speech-android-wrapper-debug-.aar
      https://repo1.maven.org/maven2//speech-android-wrapper-debug//speech-android-wrapper-debug-.pom
      https://repo1.maven.org/maven2//speech-android-wrapper-debug//speech-android-wrapper-debug-.aar
      file:/Users/friveros/Documents/PROJECTS/EXPERT ASSIST/WatsonSpeechPluginSample/platforms/android/app/WatsonSpeechPlugin/speech-android-wrapper-debug-.aar
      file:/Users/friveros/Documents/PROJECTS/EXPERT ASSIST/WatsonSpeechPluginSample/platforms/android/app/WatsonSpeechPlugin/speech-android-wrapper-debug.aar
  Required by:
      project :app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 10s
    at ChildProcess.whenDone (/Users/friveros/Documents/PROJECTS/EXPERT ASSIST/WatsonSpeechPluginSample/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:557:12)
(node:95852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:95852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Franciscos-MacBook-Pro:WatsonSpeechPluginSample friveros$

**Comment by mihui** [comment]
Hi @foward , please take a look at the new sample and try. The build settings has been updated also in the plugin repo.
